FROM python:3.12-slim

WORKDIR /app
# Create a non-root user and change ownership of /app
RUN useradd -ms /bin/bash appuser && chown -R appuser /app

COPY pyproject.toml .
COPY ods_exd_api_box/ ./ods_exd_api_box/
RUN pip3 install --upgrade pip && pip3 install '.[simple]'

COPY tests/simple/file_simple_example.py ./

USER appuser
# Start server
CMD [ "python3", "file_simple_example.py"]
